Adjusting the output of the summary.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -109,6 +109,7 @@ jobs:
           kubectl version --client >> install-tools.log 2>&1 || echo "Kubectl failed" >> install-tools.log
           yq --version >> install-tools.log 2>&1 || echo "YQ failed" >> install-tools.log
           argocd version --client >> install-tools.log 2>&1 || echo "ArgoCD failed" >> install-tools.log
+          argo version >> install-tools.log 2>&1 || echo "Argo failed" >> install-tools.log
           echo "## 📜 Raw Failure Logs:" >> install-tools.log
           cat install-tools.log
 
@@ -120,7 +121,6 @@ jobs:
           echo "- Kubectl Version: $(kubectl version --client --short)" >> $GITHUB_STEP_SUMMARY
           echo "- YQ Version: $(yq --version)" >> $GITHUB_STEP_SUMMARY
           echo "- ArgoCD Version: $(argocd version --client)" >> $GITHUB_STEP_SUMMARY
-          echo "- Custom Command Output: curl -I https://www.google.com" >> $GITHUB_STEP_SUMMARY
 
       - name: Install Tools Summary (Failure)
         if: failure()
